function [vyf,wf] = DiscreteCollisionPt2(I,e,l,m,th,vgiy,wi)
%DISCRETECOLLISIONPT2
%    [VYF,WF] = DISCRETECOLLISIONPT2(I,E,L,M,TH,VGIY,WI)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    14-Jul-2014 16:08:17

t2 = sin(th);
t3 = l.^2;
t4 = t2.^2;
t5 = I.*4.0;
t6 = m.*t3.*t4;
t7 = t5+t6;
t8 = 1.0./t7;
vyf = t8.*(I.*e.*vgiy.*-4.0+I.*l.*t2.*wi.*2.0+m.*t3.*t4.*vgiy+I.*e.*l.*t2.*wi.*2.0);
if nargout > 1
    wf = t8.*(I.*wi.*4.0+l.*m.*t2.*vgiy.*2.0+e.*l.*m.*t2.*vgiy.*2.0-e.*m.*t3.*t4.*wi);
end
